# Custom configuration

/etc/config/network
/etc/config/wireless
/etc/config/firewall
/etc/config/dhcp
/etc/config/system

/etc/sysctl.conf
/etc/dnsmasq.conf
/etc/dnsmasq.d/

/etc/init.d/zapret
/etc/rc.local
/etc/zapret-bypass-ips.txt

/usr/bin/siteekle
/usr/bin/banned-guncelle

/etc/crontabs/root

/opt/zapret/